"""Interactive setup for the Skool → Google Sheets sync.

Usage:
    python scripts/setup.py

The script will:
  1. Ask for Skool credentials, community URLs, and Google Sheets details.
  2. Ask whether to authenticate with a service account JSON or an
     OAuth 2.0 client ID/secret.
  3. Copy the service account JSON to the project (if chosen).
  4. Write a ready-to-use .env file.
  5. Generate a one-click run script (run_sync.sh / run_sync.bat).
  6. Optionally install a daily cron job (macOS/Linux) or print Windows
     Task Scheduler instructions.
"""

from __future__ import annotations

import getpass
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"
RUN_SH = PROJECT_ROOT / "scripts" / "run_sync.sh"
RUN_BAT = PROJECT_ROOT / "scripts" / "run_sync.bat"
CREDENTIALS_DST = PROJECT_ROOT / "data" / "credentials.json"


def _ask(prompt: str, default: str | None = None, password: bool = False) -> str:
    full_prompt = f"{prompt}" + (f" [{default}]" if default else "") + ": "
    if password:
        value = getpass.getpass(full_prompt)
    else:
        value = input(full_prompt)
    return value.strip() or (default or "")


def _extract_spreadsheet_id(value: str) -> str:
    """Accept a raw spreadsheet ID or a full Google Sheets URL."""
    value = value.strip()
    if "/spreadsheets/d/" in value:
        match = re.search(r"/spreadsheets/d/([a-zA-Z0-9_-]+)", value)
        if match:
            return match.group(1)
    return value


def _copy_credentials(src: Path, dst: Path) -> None:
    if not src.exists():
        raise FileNotFoundError(f"Service account credentials not found: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _write_env(config: dict[str, str]) -> None:
    if ENV_PATH.exists():
        backup = ENV_PATH.with_suffix(".env.backup")
        shutil.copy2(ENV_PATH, backup)
        print(f"Existing .env backed up to {backup}")

    lines = [
        "# Skool authentication (passed to the Apify actor)",
        f"SKOOL_EMAIL={config['skool_email']}",
        f"SKOOL_PASSWORD={config['skool_password']}",
        "",
        "# Community URLs (full URL or just the community slug)",
        f"FREE_COMMUNITY_URL={config['free_community_url']}",
        f"PAID_COMMUNITY_URL={config['paid_community_url']}",
        "",
        "# Google Sheets sink (required)",
        f"GOOGLE_SHEETS_SPREADSHEET_ID={config['google_sheets_spreadsheet_id']}",
        f"GOOGLE_SHEETS_MEMBERS_SHEET={config['google_sheets_members_sheet']}",
        f"GOOGLE_SHEETS_DAILY_METRICS_SHEET={config['google_sheets_daily_metrics_sheet']}",
        "",
        "# Google Sheets auth: service account OR OAuth client credentials",
        f"GOOGLE_SHEETS_CREDENTIALS_PATH={config['google_sheets_credentials_path']}",
        f"GOOGLE_CLIENT_ID={config.get('google_client_id', '')}",
        f"GOOGLE_CLIENT_SECRET={config.get('google_client_secret', '')}",
        f"GOOGLE_OAUTH_TOKEN_PATH={config['google_oauth_token_path']}",
        "",
        "# Apify export backend",
        "APIFY_API_TOKEN=",
        "APIFY_ACTOR_ID=cristiantala/skool-all-in-one-api",
        "",
        "# Skool cookie caching (auto-managed, leave as-is)",
        "SKOOL_COOKIES_PATH=./data/skool_cookies.json",
        "SKOOL_COOKIES_REFRESH_HOURS=24",
        "",
        "# Local paths",
        "DOWNLOAD_DIR=./data/raw",
        "PROCESSED_DIR=./data/processed",
        "REPORTS_DIR=./data/reports",
        "",
        "# Operational",
        f"TIMEZONE={config.get('timezone', 'UTC')}",
        "DRY_RUN=false",
        "BACKFILL_MODE=false",
        f"LOG_LEVEL={config.get('log_level', 'INFO')}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")


def _generate_run_scripts(python_path: Path) -> None:
    """Create run_sync.sh (and .bat) so the owner can run the sync with one click."""
    sh = f"""#!/usr/bin/env bash
# Auto-generated by scripts/setup.py
set -euo pipefail
cd "{PROJECT_ROOT}"
"{python_path}" -m src.main "$@"
"""
    bat = f"""@echo off
REM Auto-generated by scripts/setup.py
cd /d "{PROJECT_ROOT}"
"{python_path}" -m src.main %*
pause
"""
    RUN_SH.write_text(sh, encoding="utf-8")
    RUN_SH.chmod(0o755)
    RUN_BAT.write_text(bat, encoding="utf-8")
    print(f"Created {RUN_SH}")
    print(f"Created {RUN_BAT}")


def _parse_time(time_str: str) -> tuple[int, int]:
    match = re.match(r"^(\d{1,2}):(\d{2})$", time_str.strip())
    if not match:
        raise ValueError("Time must be in HH:MM format, e.g. 06:00")
    hour = int(match.group(1))
    minute = int(match.group(2))
    if not (0 <= hour <= 23 and 0 <= minute <= 59):
        raise ValueError("Hour must be 0-23 and minute 0-59")
    return hour, minute


def _install_cron(time_str: str, python_path: Path) -> None:
    hour, minute = _parse_time(time_str)
    marker = "# skool-sync daily run"
    command = f"{minute} {hour} * * * cd {PROJECT_ROOT} && {python_path} -m src.main >> {PROJECT_ROOT}/data/cron.log 2>&1"

    try:
        result = subprocess.run(
            ["crontab", "-l"],
            capture_output=True,
            text=True,
            check=False,
        )
        existing = result.stdout if result.returncode == 0 else ""
        if marker in existing:
            print("A skool-sync cron job already exists; skipping.")
            return
        new_crontab = existing.rstrip() + f"\n{marker}\n{command}\n"
        subprocess.run(
            ["crontab", "-"],
            input=new_crontab,
            text=True,
            check=True,
        )
        print(f"Installed daily cron job at {time_str} (system time).")
    except FileNotFoundError:
        print("crontab not found on this system. Install cron manually:")
        print(f"  {command}")


def _windows_scheduler_instructions(time_str: str, python_path: Path) -> None:
    print("\n--- Windows Task Scheduler ---")
    print("1. Open Task Scheduler and create a Basic Task.")
    print("2. Trigger: Daily at the time you chose.")
    print(f"3. Action: Start a program -> {python_path}")
    print(f"   Add arguments: -m src.main")
    print(f"   Start in: {PROJECT_ROOT}")
    print(f"4. Use the generated batch file as a shortcut: {RUN_BAT}\n")


def main() -> None:
    print("=" * 60)
    print("Skool Sync – Owner Setup")
    print("=" * 60)
    print("This will create a .env file and prepare the daily sync.\n")

    # ------------------------------------------------------------------
    # 1. Collect configuration
    # ------------------------------------------------------------------
    skool_email = _ask("Skool email")
    skool_password = _ask("Skool password", password=True)

    free_community_url = _ask("Free community URL (or slug)")
    paid_community_url = _ask("Paid community URL (or slug)")

    # ------------------------------------------------------------------
    # Google Sheets auth: service account vs OAuth
    # ------------------------------------------------------------------
    auth_method = _ask("Google Sheets auth: service-account (s) or OAuth client (o)? [s/o]", default="s").lower()
    use_oauth = auth_method.startswith("o")

    google_client_id = ""
    google_client_secret = ""
    if use_oauth:
        google_client_id = _ask("Google client ID")
        google_client_secret = _ask("Google client secret", password=True)
        credentials_src: Path | None = None
    else:
        credentials_input = _ask(
            "Path to Google service account JSON",
            default="./data/credentials.json",
        )
        credentials_src = Path(credentials_input).expanduser().resolve()
        if not credentials_src.exists():
            print(f"\nERROR: Google service account JSON not found: {credentials_src}")
            print("Please download the JSON key from Google Cloud Console and try again.")
            sys.exit(1)

        if credentials_src != CREDENTIALS_DST.resolve():
            _copy_credentials(credentials_src, CREDENTIALS_DST)
            print(f"Copied credentials to {CREDENTIALS_DST}")

    spreadsheet_input = _ask("Google Sheets spreadsheet ID or full URL")
    spreadsheet_id = _extract_spreadsheet_id(spreadsheet_input)

    members_sheet = _ask("Members sheet name", default="Members")
    metrics_sheet = _ask("Daily metrics sheet name", default="DailyMetrics")

    schedule = _ask("Schedule a daily sync now? (y/N)", default="N").lower().startswith("y")
    schedule_time = "06:00"
    if schedule:
        schedule_time = _ask("What time should it run? (HH:MM, 24-hour)", default="06:00")

    # ------------------------------------------------------------------
    # 2. Write .env and helper scripts
    # ------------------------------------------------------------------
    config = {
        "skool_email": skool_email,
        "skool_password": skool_password,
        "free_community_url": free_community_url,
        "paid_community_url": paid_community_url,
        "google_sheets_credentials_path": "./data/credentials.json",
        "google_sheets_spreadsheet_id": spreadsheet_id,
        "google_sheets_members_sheet": members_sheet,
        "google_sheets_daily_metrics_sheet": metrics_sheet,
        "google_client_id": google_client_id,
        "google_client_secret": google_client_secret,
        "google_oauth_token_path": "./data/google_oauth_token.json",
        "timezone": "UTC",
        "log_level": "INFO",
    }

    # When using OAuth, use a non-existent sentinel for the service account
    # path so a stale file does not silently take precedence in
    # GoogleSheetsSink.
    if use_oauth:
        config["google_sheets_credentials_path"] = "./data/.oauth-no-service-account"

    # ------------------------------------------------------------------
    # 2a. Validate inputs
    # ------------------------------------------------------------------
    missing: list[str] = []
    if not config["skool_email"] or "@" not in config["skool_email"]:
        missing.append("a valid Skool email")
    if not config["skool_password"]:
        missing.append("a Skool password")
    if not config["free_community_url"]:
        missing.append("a free community URL")
    if not config["paid_community_url"]:
        missing.append("a paid community URL")
    if not config["google_sheets_spreadsheet_id"]:
        missing.append("a Google Sheets spreadsheet ID")

    has_service_account = Path(config["google_sheets_credentials_path"]).exists()
    has_oauth = bool(config["google_client_id"]) and bool(config["google_client_secret"])
    if not (has_service_account or has_oauth):
        missing.append("either a service account JSON at data/credentials.json or GOOGLE_CLIENT_ID + GOOGLE_CLIENT_SECRET")

    if config["free_community_url"].lower().strip().rstrip("/") == config["paid_community_url"].lower().strip().rstrip("/"):
        missing.append("different free and paid community URLs")
    if missing:
        print("\nERROR: Please provide " + ", ".join(missing))
        sys.exit(1)

    if schedule:
        try:
            _parse_time(schedule_time)
        except ValueError as exc:
            print(f"\nERROR: Invalid schedule time: {exc}")
            sys.exit(1)

    _write_env(config)
    print(f"\nWrote configuration to {ENV_PATH}")

    # Determine the Python interpreter to use (prefer the active venv)
    python_path = Path(sys.executable).resolve()
    _generate_run_scripts(python_path)

    # ------------------------------------------------------------------
    # 3. Scheduling
    # ------------------------------------------------------------------
    if schedule:
        system = platform.system()
        if system in ("Darwin", "Linux"):
            _install_cron(schedule_time, python_path)
        elif system == "Windows":
            _windows_scheduler_instructions(schedule_time, python_path)
        else:
            print(f"Automatic scheduling not supported on {system}.")
            print("Run the sync manually or schedule scripts/run_sync.sh.")

    # ------------------------------------------------------------------
    # 4. Final instructions
    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print("\nNext steps:")
    if use_oauth:
        print("  1. Authorize Google Sheets access: python scripts/google_auth.py")
        print("     (this opens a browser; on a headless server use --console)")
        login_step = 2
    else:
        print(f"  1. Share your Google Sheet with the service account email in {CREDENTIALS_DST}")
        print(f"     (open the JSON to find client_email).")
        login_step = 2
    print(f"  {login_step}. Test the sync: python -m src.main --dry-run")
    print(f"  {login_step + 1}. Run for real:   python -m src.main")
    if schedule:
        print(f"  {login_step + 2}. The daily sync is scheduled at {schedule_time}.")
    print("\nIf your Apify token ever expires, update APIFY_API_TOKEN in .env and restart.\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
        sys.exit(1)
